# Generated by Django 4.0.4 on 2023-10-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_tovar_cat_tovar_price_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
