# Generated by Django 4.0.4 on 2023-10-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_tovar_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otziv',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
